/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UkBadge {
    }
}
declare global {
    interface HTMLUkBadgeElement extends Components.UkBadge, HTMLStencilElement {
    }
    var HTMLUkBadgeElement: {
        prototype: HTMLUkBadgeElement;
        new (): HTMLUkBadgeElement;
    };
    interface HTMLElementTagNameMap {
        "uk-badge": HTMLUkBadgeElement;
    }
}
declare namespace LocalJSX {
    interface UkBadge {
    }
    interface IntrinsicElements {
        "uk-badge": UkBadge;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "uk-badge": LocalJSX.UkBadge & JSXBase.HTMLAttributes<HTMLUkBadgeElement>;
        }
    }
}
